# Generated by Django 5.2.5 on 2025-08-13 03:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=10)),
                ('date', models.DateField()),
                ('median_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_per_sqft', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_listings', models.PositiveIntegerField()),
                ('new_listings', models.PositiveIntegerField()),
                ('pending_sales', models.PositiveIntegerField()),
                ('closed_sales', models.PositiveIntegerField()),
                ('days_on_market', models.PositiveIntegerField()),
                ('months_of_inventory', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_drops_pct', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('city', 'state', 'zip_code', 'period', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PropertyValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('bedrooms', models.PositiveSmallIntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=4)),
                ('square_feet', models.PositiveIntegerField()),
                ('lot_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('year_built', models.PositiveIntegerField()),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('confidence_score', models.PositiveSmallIntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('valuation_history', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None)),
            ],
            options={
                'unique_together': {('address_line1', 'city', 'state', 'zip_code')},
            },
        ),
    ]
