# Generated by Django 5.2.5 on 2025-08-13 03:17

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_codes', models.CharField(max_length=255)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('boundary_points', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('median_home_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('median_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('median_age', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('median_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_growth_1yr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rent_growth_1yr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('walk_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('transit_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bike_score', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violent_crime_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('property_crime_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('safety_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('data_year', models.PositiveSmallIntegerField()),
                ('neighborhood', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crime_data', to='neighborhoods.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('grocery', 'Grocery Store'), ('retail', 'Retail'), ('park', 'Park'), ('gym', 'Gym'), ('hospital', 'Hospital'), ('pharmacy', 'Pharmacy'), ('entertainment', 'Entertainment'), ('transit', 'Transit'), ('other', 'Other')], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_of_interest', to='neighborhoods.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('elementary', 'Elementary School'), ('middle', 'Middle School'), ('high', 'High School'), ('charter', 'Charter School'), ('private', 'Private School')], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('enrollment', models.PositiveIntegerField(blank=True, null=True)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='neighborhoods.neighborhood')),
            ],
        ),
    ]
